theme: minima
title: Surprise
description: Welcome To this site Stay tuned for surprises!
author: Prince Kumar
email: pkpkk@pkpkk.eu.org
github_username: pk-628996
twitter_username: mytwitter
url: "https://pkpkk.eu.org"
baseurl: "/site"
permalink: /blog/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
